### ISSUE TITLE
Module 2

### ISSUE THREAD

**Issue by bnvmxm** [FezZHD/flutter_mentoring_tasks#1]
Интересно с SingleChildScrollView + Wrap
Не совсем понятно, почему MaterialButton обернут в Builder
По локализации очень рекомендую -
https://marketplace.visualstudio.com/items?itemName=esskar.vscode-flutter-i18n-json

**Comment by fezzhd** [comment]
Я SnackBar показываю по клику на кнопку, без него валится, ибо Scafford не находит
