### ISSUE TITLE
Module 3

### ISSUE THREAD

**Issue by bnvmxm** [FezZHD/flutter_mentoring_tasks#2]
/// doesn't work on iOS
- Looks it needs a change on ios platform specific code:

https://api.flutter.dev/flutter/services/SystemNavigator/pop.html

**Comment by bnvmxm** [comment]
Also there's a bug - when I double-tap the 'back' button on the first screen (or tap it when the confirmation dialog is shown)

**Comment by fezzhd** [comment]
> /// doesn't work on iOS
> 
>     * Looks it needs a change on ios platform specific code:
> 
> 
> https://api.flutter.dev/flutter/services/SystemNavigator/pop.html

As I read, that we [cannot exit iOS app programmatically](https://stackoverflow.com/questions/23391706/quit-ios-application-programmatically-with-uialertview/23391752).

I tried with `SystemChannel`, but result is the same.

**Comment by bnvmxm** [comment]
> > /// doesn't work on iOS
> > ```
> > * Looks it needs a change on ios platform specific code:
> > ```
> > 
> > 
> > https://api.flutter.dev/flutter/services/SystemNavigator/pop.html
> 
> As I read, that we [cannot exit iOS app programmatically](https://stackoverflow.com/questions/23391706/quit-ios-application-programmatically-with-uialertview/23391752).
> 
> I tried with `SystemChannel`, but result is the same.

Ok, not an issue in this module

**Comment by fezzhd** [comment]
Transparent input disabled.
